services:
  ai_interviewer_backend:
    image: ghcr.io/${org}/ai-interviewer-backend:${AI_INTERVIEWER_BACKEND_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    restart: always
    environment:
      JWTSECRET: ${JWTSECRET:?JWTSECRET is not set}
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY:?OPEN_AI_API_KEY is not set}
      GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY:?GOOGLE_AI_API_KEY is not set}
      FRONTEND_LINK: ${FRONTEND_LINK:?FRONTEND_LINK is not set}
      RUNTIME: ${env:?env is not set}
      INTERVIEWER_FRONTEND_LINK: ${INTERVIEWER_FRONTEND_LINK:?INTERVIEWER_FRONTEND_LINK is not set}
      PITCH_FRONTEND_LINK: ${PITCH_FRONTEND_LINK:?PITCH_FRONTEND_LINK is not set}
      SAS_TOKEN: ${SAS_TOKEN:?SAS_TOKEN is not set}
      CONTAINER_NAME: ${AZURE_BLOB_CONTAINER_NAME:?AZURE_BLOB_CONTAINER_NAME is not set}
      STORAGE_ACCOUNT_URL: ${STORAGE_ACCOUNT_URL:?STORAGE_ACCOUNT_URL is not set}
      MAX_ALLOWED_QUESTIONS: ${MAX_ALLOWED_QUESTIONS:?MAX_ALLOWED_QUESTIONS is not set}
      EMAIL_HOST: ${EMAIL_HOST:?EMAIL_HOST is not set}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER:?EMAIL_HOST_USER is not set}
      AZURE_EMAIL_CONNECTION_STRING: ${AZURE_EMAIL_CONNECTION_STRING:?AZURE_EMAIL_CONNECTION_STRING is not set}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:?CELERY_BROKER_URL is not set}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:?CELERY_RESULT_BACKEND is not set}
      CELERY_TIMEZONE: ${CELERY_TIMEZONE:?CELERY_TIMEZONE is not set}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:?AZURE_STORAGE_CONNECTION_STRING is not set}
      AZURE_STORAGE_CONTAINER_NAME: ${AZURE_STORAGE_CONTAINER_NAME:?AZURE_STORAGE_CONTAINER_NAME is not set}
      AZURE_STORAGE_ACCOUNT_KEY: ${AZURE_STORAGE_ACCOUNT_KEY:?AZURE_STORAGE_ACCOUNT_KEY is not set}
      ELEVEN_LABS_API_KEY: ${ELEVEN_LABS_API_KEY:?ELEVEN_LABS_API_KEY is not set}
      ENVIRONMENT: ${LLM_ENVIRONMENT:?LLM_ENVIRONMENT is not set}
      HUGGING_FACE_TOKEN: ${HUGGING_FACE_TOKEN:?HUGGING_FACE_TOKEN is not set}
      ISB_JOB_ID: ${ISB_JOB_ID:?ISB_JOB_ID is not set}
      DB_NAME: ${POSTGRES_DB:?POSTGRES_DB is not set}
      DB_USER: ${POSTGRES_USER:?POSTGRES_USER is not set}
      DB_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set}
      DB_HOST: ${DB_HOST:?DB_HOST is not set}
      DB_PORT: ${DB_PORT:?DB_PORT is not set}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:?GOOGLE_APPLICATION_CREDENTIALS is not set}
    volumes:
      - ./log/:/app/log
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"


  celery_worker:
    image: ghcr.io/${org}/ai-interviewer-backend:${AI_INTERVIEWER_BACKEND_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    restart: always
    depends_on:
      - ai_interviewer_backend
    environment:
      JWTSECRET: ${JWTSECRET:?JWTSECRET is not set}
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY:?OPEN_AI_API_KEY is not set}
      GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY:?GOOGLE_AI_API_KEY is not set}
      FRONTEND_LINK: ${FRONTEND_LINK:?FRONTEND_LINK is not set}
      RUNTIME: ${env:?env is not set}
      INTERVIEWER_FRONTEND_LINK: ${INTERVIEWER_FRONTEND_LINK:?INTERVIEWER_FRONTEND_LINK is not set}
      PITCH_FRONTEND_LINK: ${PITCH_FRONTEND_LINK:?PITCH_FRONTEND_LINK is not set}
      SAS_TOKEN: ${SAS_TOKEN:?SAS_TOKEN is not set}
      CONTAINER_NAME: ${AZURE_BLOB_CONTAINER_NAME:?AZURE_BLOB_CONTAINER_NAME is not set}
      STORAGE_ACCOUNT_URL: ${STORAGE_ACCOUNT_URL:?STORAGE_ACCOUNT_URL is not set}
      MAX_ALLOWED_QUESTIONS: ${MAX_ALLOWED_QUESTIONS:?MAX_ALLOWED_QUESTIONS is not set}
      EMAIL_HOST: ${EMAIL_HOST:?EMAIL_HOST is not set}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER:?EMAIL_HOST_USER is not set}
      AZURE_EMAIL_CONNECTION_STRING: ${AZURE_EMAIL_CONNECTION_STRING:?AZURE_EMAIL_CONNECTION_STRING is not set}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:?CELERY_BROKER_URL is not set}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:?CELERY_RESULT_BACKEND is not set}
      CELERY_TIMEZONE: ${CELERY_TIMEZONE:?CELERY_TIMEZONE is not set}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:?AZURE_STORAGE_CONNECTION_STRING is not set}
      AZURE_STORAGE_CONTAINER_NAME: ${AZURE_STORAGE_CONTAINER_NAME:?AZURE_STORAGE_CONTAINER_NAME is not set}
      AZURE_STORAGE_ACCOUNT_KEY: ${AZURE_STORAGE_ACCOUNT_KEY:?AZURE_STORAGE_ACCOUNT_KEY is not set}
      ELEVEN_LABS_API_KEY: ${ELEVEN_LABS_API_KEY:?ELEVEN_LABS_API_KEY is not set}
      ENVIRONMENT: ${LLM_ENVIRONMENT:?LLM_ENVIRONMENT is not set}
      HUGGING_FACE_TOKEN: ${HUGGING_FACE_TOKEN:?HUGGING_FACE_TOKEN is not set}
      ISB_JOB_ID: ${ISB_JOB_ID:?ISB_JOB_ID is not set}
      DB_NAME: ${POSTGRES_DB:?POSTGRES_DB is not set}
      DB_USER: ${POSTGRES_USER:?POSTGRES_USER is not set}
      DB_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set}
      DB_HOST: ${DB_HOST:?DB_HOST is not set}
      DB_PORT: ${DB_PORT:?DB_PORT is not set}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:?GOOGLE_APPLICATION_CREDENTIALS is not set}
    entrypoint: ["celery", "-A", "backend.celery", "worker", "--loglevel=info"]
